### PR TITLE
Include plookup in opening proof polys

### PR DESCRIPTION
**Pull request by lopeetall**

### CODE REVIEW

**Comment by lopeetall** [comment]
Changes I made here affect many tests which are now failing. Will work on updating the old tests next.

**Comment by Bounce23** [comment]
I would say until this is ready to go into `dusk-network:composer_plookup`, then we should turn it to draft.

**Comment by lopeetall** [comment]
It looks like the tests that fail are those that involve proof/proverkey serialization or those that run a verifier. I can push some new changes that fix the serialization issues if that is helpful.

**Comment by Bounce23** [comment]
Closed this PR as #366 was merged containing these changes.

**Pull request closed without merging**
