### PR TITLE
Multizip version of product argument

### PR DESCRIPTION
**Pull request by lopeetall**
Rayon provides a `multizip` struct which can zip up to 12 iterators in parallel. This is a new function `multizip_compute_permutation_poly` that ought to perform the same computation as `fast_compute_permutation_poly` but is easier to adapt to a change in the number of wires or a change in the formula used in the numerator and denominator irreducibles in the product argument.

### CODE REVIEW

**Comment by CPerezz** [comment]
Hey @lopeetall thanks for the PR. We were already using `Multizip`. But I took a look to your code and looks much cleaner and organized (we haven't invested any hours on the permutation aside for putting it to work. 

For me it will be fine to merge that, I would just need you to replace the code of the old method with the new one and check whether the tests pass.

If that's the case, I'm happy to merge it since the code will be easier to maintain and read! :)

**Comment by lopeetall** [comment]
I added a test to permutations.rs that shows this new function gives the same output as the previously used one, and swapped out the methods.

**Comment by CPerezz** [comment]
KK after debugging a while, I saw which were the errors that were causing your PR to fail. 

As I said, it had nothing to do with our changes in the repo, since the CI passed for all of them. The problem is that even the function that you implemented and the previous one used for the permutation computation were giving the same result, they were getting different input params.

Instead of receiving the `evals` as you went for, you need to `fft` the polynomials and send the resulting `BlsScalar` Vec. 
When you do that, you'll see that the inputs are different.

Also I took profit to rename your fn to `compute_permutation_poly` as the original so there's no need to have wrapper functions. Then I deleted the old `compute_permutation_poly` fn.

Since I didn't want to open a PR in your repo or commit directly here, I pushed a branch with the changes so that you can see what I did to your code. Feel free to make a PR from it to your repo or copy the code fixing the commit authors. Whatever suits better to you.

Here the link: https://github.com/metastatedev/plonk/commit/2755fb42dd6b49e1bbf46cea31ecfb2cee187f5a

Hope this helps @lopeetall

**Comment by CPerezz** [comment]
Could you update the `CHANGELOG.md` adding this changes to the `Unreleased` section? Then I can go for the review :smile:

**Comment by CPerezz** [comment]
Hey @lopeetall we will probably not ship a new version just for this changes. The idea is to keep it unreleased but merged into `master` until we have more stuff to make a proper release.

Do you mind keeping that under `Unreleased`?

**Comment by lopeetall** [comment]
Not a problem. I just didn't quite understand how to add to the changlelog. I suppose I should have put the change under the existing version number iiuc. Thanks for bearing with me--a lot of this is new to me.

**Comment by lopeetall** [comment]
Ok, I think I updated the changelog correctly this time. Thanks for bearing with me.

**Review by CPerezz — APPROVED** [review]
LGTM! Thanks @lopeetall :smile:

**Pull request merged**
