### PR TITLE
Bump bls12_381 to 0.1.5 and jujub to 0.3.10

### PR DESCRIPTION
**Pull request by vlopes11**

### CODE REVIEW

**Review by krl — APPROVED** [review]
lgtm

**Comment by CPerezz** [comment]
ACK!

**Review by CPerezz — APPROVED** [review]
ACK!

**Comment by CPerezz** [comment]
This should not be necessary since cargo will take the latest minor anyway. But whatever you want. It's not wrong to patch-bump this.

**Pull request merged**
