### PR TITLE
Take fft_const from Bls lib

### LINKED ISSUE #141: Get fft constants from Bls12_381 library
Given this:
https://github.com/dusk-network/plonk/blob/4d0fa12efe943c596531b4259ac5df0037868313/src/fft/constants.rs#L3

Expose the constants needed by fft in Bls12_381 fork (if needed) and import them instead of hard-coding them twice.

### PR DESCRIPTION
**Pull request by CPerezz**
Closes #141

Imports:
- GENERATOR
- TWO ADACITY
- ROOT_OF_UNITY

Edit: It also removes Cargo.lock form the repository.

### CODE REVIEW

**Comment by kevaundray** [comment]
We should not import one letter variables. Please change the constant in BLS from S to TWO_ADICITY , so we know what we are importing

**Comment by CPerezz** [comment]
> Please change the constant in BLS from S to TWO_ADICITY , so we know what we are importing
Ready.

**Comment by kevaundray** [comment]
> > Please change the constant in BLS from S to TWO_ADICITY , so we know what we are importing
> 
> Ready @kevaundray .

Oh, I meant can you change it in the BLS crate instead of just aliasing it

**Comment by CPerezz** [comment]
> > > Please change the constant in BLS from S to TWO_ADICITY , so we know what we are importing
> > 
> > 
> > Ready @kevaundray .
> 
> Oh, I meant can you change it in the BLS crate instead of just aliasing it

`S` was already defined on the BLS repo before we forked it. So we should not change it imo. If we want to call it like this, we can just use an alias as it is done now.

**Pull request merged**
