### PR TITLE
Removes the un-needed padding constraints

### LINKED ISSUE #205: Remove un-needed padding
Currently the constraint system is being padded so that the selector polynomials are never full of zeroes. This is because the commitment scheme will panic when trying to commit to zero degree polynomials. 

We can solve this by checking if the polynomial is the zero polynomial and then return an empty commitment

### PR DESCRIPTION
**Pull request by kevaundray**
Previously, we were padding as we could not commit to a polynomial of ZeroDegree for the selector polynomials.

This PR commits to a selector polynomial, or it returns an empty commitment.

Closes #205

### CODE REVIEW

**Comment by CPerezz** [comment]
Before merging this, we'll need to refactor the examples (circuit sizes will have changed since now `add_dummy_constraints()` adds less constraints.

This will mean that you'll need to generate a new Prep Circ as well as proofs for the 3rd example.

**Comment by CPerezz** [comment]
Also, regarding that, What happens then when we return the zero commit?
Would this affect to any of the plonk stages? Like producing circuits that will never be verificable??

**Comment by CPerezz** [comment]
Do we have any issue related to this?

**Comment by kevaundray** [comment]
> Before merging this, we'll need to refactor the examples (circuit sizes will have changed since now `add_dummy_constraints()` adds less constraints.
> 
> This will mean that you'll need to generate a new Prep Circ as well as proofs for the 3rd example.

The circuits are usually padded to the next power of two, so is this a problem?

**Comment by CPerezz** [comment]
> > Before merging this, we'll need to refactor the examples (circuit sizes will have changed since now `add_dummy_constraints()` adds less constraints.
> > This will mean that you'll need to generate a new Prep Circ as well as proofs for the 3rd example.
> 
> The circuits are usually padded to the next power of two, so is this a problem?

I mean, AFAIK if we remove the dummy constraints of the range and logic gates, this means that the circuit description has changed. And so, the data structures would need to be re-computed.

**Comment by kevaundray** [comment]
> > > Before merging this, we'll need to refactor the examples (circuit sizes will have changed since now `add_dummy_constraints()` adds less constraints.
> > > This will mean that you'll need to generate a new Prep Circ as well as proofs for the 3rd example.
> > 
> > 
> > The circuits are usually padded to the next power of two, so is this a problem?
> 
> I mean, AFAIK if we remove the dummy constraints of the range and logic gates, this means that the circuit description has changed. And so, the data structures would need to be re-computed.

I'm not sure I'm following, the circuit should still be satisfied

**Comment by kevaundray** [comment]
> Do we have any issue related to this?

No, it was in the comments. I will create a corresponding issue now

**Comment by CPerezz** [comment]
> > > > Before merging this, we'll need to refactor the examples (circuit sizes will have changed since now `add_dummy_constraints()` adds less constraints.
> > > > This will mean that you'll need to generate a new Prep Circ as well as proofs for the 3rd example.
> > > 
> > > 
> > > The circuits are usually padded to the next power of two, so is this a problem?
> > 
> > 
> > I mean, AFAIK if we remove the dummy constraints of the range and logic gates, this means that the circuit description has changed. And so, the data structures would need to be re-computed.
> 
> I'm not sure I'm following, the circuit should still be satisfied

But you removed three constraints from the `add_dummy_constraints` which basically means that the circuit that we have stored and preprocessed serialized is no longer valid i think.

Try to run the  examples when you're done to see if it works!

**Comment by kevaundray** [comment]
> > > > > Before merging this, we'll need to refactor the examples (circuit sizes will have changed since now `add_dummy_constraints()` adds less constraints.
> > > > > This will mean that you'll need to generate a new Prep Circ as well as proofs for the 3rd example.
> > > > 
> > > > 
> > > > The circuits are usually padded to the next power of two, so is this a problem?
> > > 
> > > 
> > > I mean, AFAIK if we remove the dummy constraints of the range and logic gates, this means that the circuit description has changed. And so, the data structures would need to be re-computed.
> > 
> > 
> > I'm not sure I'm following, the circuit should still be satisfied
> 
> But you removed three constraints from the `add_dummy_constraints` which basically means that the circuit that we have stored and preprocessed serialized is no longer valid i think.
> 
> Try to run the examples when you're done to see if it works!

Oh right, the preprocessed circuit is hardcoded. We should change this as changes to the constraint system will mean we will need to keep changing these examples, which is tedious.

**Comment by CPerezz** [comment]
> > > > > > Before merging this, we'll need to refactor the examples (circuit sizes will have changed since now `add_dummy_constraints()` adds less constraints.
> > > > > > This will mean that you'll need to generate a new Prep Circ as well as proofs for the 3rd example.
> > > > > 
> > > > > 
> > > > > The circuits are usually padded to the next power of two, so is this a problem?
> > > > 
> > > > 
> > > > I mean, AFAIK if we remove the dummy constraints of the range and logic gates, this means that the circuit description has changed. And so, the data structures would need to be re-computed.
> > > 
> > > 
> > > I'm not sure I'm following, the circuit should still be satisfied
> > 
> > 
> > But you removed three constraints from the `add_dummy_constraints` which basically means that the circuit that we have stored and preprocessed serialized is no longer valid i think.
> > Try to run the examples when you're done to see if it works!
> 
> Oh right, the preprocessed circuit is hardcoded. We should change this as changes to the constraint system will mean we will need to keep changing these examples, which is tedious.

Ping me once you're done and I'll recompile the examples data structures that we need to store serialized and will commit the changes!

**Comment by kevaundray** [comment]
I've opened two issues #206 and #207  regarding the Examples folder. Will merge this in and track those issues

**Pull request merged**
