### PR TITLE
Docs skeleton

### PR DESCRIPTION
**Pull request by Bounce23**
This PR is the skeleton for the docs, to be inserted in Master so that an idea of the format is gained for all parties who want to work on docs.

### CODE REVIEW

**Comment by Bounce23** [comment]
I found a great feature online, [here](https://github.com/rust-lang/rust/issues/44732). It lets us link the docs in lib.rs and make a new module out of it all. For me to mitigate the errors, I had to go to rust nightly, but then I started getting errors in the build for other parts across the branch (not related to the documentation files). Perhaps its just a toolchain issue but i'm not sure. Any ideas why this is? @CPerezz @decentralisedkev 

 For now, I've just reverted the changes and will add them to my local branch general docs (version permitting).

**Comment by CPerezz** [comment]
> I found a great feature online, [here](https://github.com/rust-lang/rust/issues/44732). It lets us link the docs in lib.rs and make a new module out of it all. For me to mitigate the errors, I had to go to rust nightly, but then I started getting errors in the build for other parts across the branch (not related to the documentation files). Perhaps its just a toolchain issue but i'm not sure. Any ideas why this is? @CPerezz @decentralisedkev
> 
> For now, I've just reverted the changes and will add them to my local branch general docs (version permitting).

Before we jump into trying this, it might be better to have a solid structure for our models first of all, but we can look it on the future, seems nice!

**Comment by CPerezz** [comment]
Travis err: `error[E0554]: `#![feature]` may not be used on the stable release channel`

Will modify the config so you don't get errors on each build @Bounce23

**Comment by Bounce23** [comment]
Done @CPerezz

**Pull request merged**
